# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Bowman
email: mbowman2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Toronto-based Ruby on Rails developer. Looking to build my portfolio,
  and make contacts in the industry here in Toronto. Get in touch!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bowmanmike.com" # the base hostname & protocol for your site
twitter_username: mbowman2
github_username:  bowmanmike

# Build settings
markdown: kramdown
